language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

before_install:

script:
  - mvn clean package -DskipTests=true

after_success:
  - cd ./target
  - git init
  - git config user.name "Starrier"
  - git config user.email "1342878298@qq.com"
  - git add iShare.war
  - git commit -m "travis-ci"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
  - - mvn clean -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID cobertura:cobertura coveralls:report
  - mvn clean test jacoco:report coveralls:report
  - mvn org.eluder.coveralls:coveralls-maven-plugin:report -DrepoToken="${COVERALLS_TOKEN}"
  - mvn sonar:sonar -Dsonar.projectKey=Starrier_iShare  -Dsonar.organization=starrier -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login="${SONAR_TOKEN}"

branches:
  only:
    - master

notifications:
  webhooks:https://oapi.dingtalk.com/robot/send?access_token=3ee396e877598f75bfebedec9f226f9f286037437443ac0c429b2aaa6df0d10a

env:
  global:
    - GH_REF=https://github.com/Starrier/iShare.git
